name: Update READMEE
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Mhmdabed11/md-replacer@0.24
        with:
          USERNAME: "mhmdabed11"
